name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - run: npm ci
      - run: npm run jserver
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-646e9749f59d081fceee5769-09a4c7ba9f7e3a23e4adb8ec2e4669bffe
      - name: Run API tests
        run: |
          postman collection run "2178209-7133d2d7-91bc-417b-a885-9987e6cb137e"